all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    routers:
      hosts:
        r1:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-r1
        r2:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-r2
    aaa:
      hosts:
        radius:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-radius
          ansible_python_interpreter: /usr/bin/python3
