all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    routers:
      hosts:
        r1:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-r1
          ansible_python_interpreter: /usr/bin/python3.10
        r2:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-r2
          ansible_python_interpreter: /usr/bin/python3.10

    aaa:
      hosts:
        radius:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-radius
          ansible_python_interpreter: /usr/bin/python3

    workstations:
      hosts:
        pc1:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-pc1
        pc2:
          ansible_connection: community.docker.docker
          ansible_host: clab-basic-pc2

